[project]
name = "planit"
version = "0.9.1"
authors = [
    {name = "Philip Carter", email = "p.carter@bristol.ac.uk"},
]
description = "The PLANetary Impact Toolkit provides tools for accessing, manipulating, and analysing smoothed particle hydrodynamcis (SPH) impact simulation data, and creating planets for SPH impact simulations."
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]
dependencies = ["numpy","scipy","matplotlib","numba","h5py","seagen"]
[project.urls]
Homepage = "https://github.com/PhilJCarter/planit"