# This workflow will install Python dependencies, and run tests with a variety of Python versions

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }} on ${{matrix.os}}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pytest-cov
        python -m pip install numpy scipy matplotlib seagen==1.5 numba h5py cmasher
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install planit
      run: |
        pip install -e .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --cov=planit --cov-report html:cov_html
        
    - if: ${{ (matrix.python-version == '3.10') && (matrix.os == 'ubuntu-latest') }}
      name: badge
      run: |
        pip install coverage-badge
        coverage-badge -o coverage.svg -f
        # Tell git who is making the commit
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        
        git checkout -B gh-pages
        
        # Add the SVG and commit it
        git add coverage.svg
        git add cov_html/*
        git commit -m "Update coverage badge" || echo "No changes to commit"
        
        # Push the branch forcefully
        git push origin gh-pages -f
